# MODEL TRAINING

### 1) importing data required packages

##### importing Numpy, Pandas, Seaborn, Maplotlib and Warning library

In [11]:
# basic import 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# model import
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostClassifier, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import cross_val_score, RandomizedSearchCV
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings('ignore')

#### import csv data and pandas dataframe

In [4]:
df = pd.read_csv('data/stud.csv')

#### show top 5 records

In [5]:
df.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [6]:
x = df.drop(columns=['math_score'],axis=1)

In [8]:
x.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [9]:
y = df['math_score']

In [10]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [12]:
# column transformer with 3 typres of transformation
num_features = x.select_dtypes(exclude='object').columns
cat_features = x.select_dtypes(include='object').columns

numeric_transformer = StandardScaler()
hot_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", hot_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [13]:
x= preprocessor.fit_transform(x)

In [14]:
x.shape

(1000, 19)

In [16]:
x

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [17]:
# split data between train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [18]:
x_train.shape, x_test.shape

((800, 19), (200, 19))